package vitor.dev.com.Cadastro.Usuario.Exceptions.CustomExceptions;

public class RecursoNaoEncontradoException extends RuntimeException {

    public RecursoNaoEncontradoException(String message) {
        super(message);
    }
}